import { useEffect, useMemo, useState } from 'react';
import { routeFor } from './routes.js';
import { siteData } from './siteData.js';

function navigate(path) {
  window.history.pushState({}, '', path);
  window.dispatchEvent(new PopStateEvent('popstate'));
}

export default function App() {
  const [path, setPath] = useState(window.location.pathname);
  const [cartCount, setCartCount] = useState(0);
  const route = useMemo(() => routeFor(path), [path]);

  useEffect(() => {
    const onRoute = () => setPath(window.location.pathname);
    window.addEventListener('popstate', onRoute);
    return () => window.removeEventListener('popstate', onRoute);
  }, []);

  return (
    <div className="site-shell">
      <header className="nav">
        <button className="brand" onClick={() => navigate('/')}>
          {siteData.businessName || 'Forge'}<small>{siteData.location || 'Generated by Glondia'}</small>
        </button>
        <nav>
          {siteData.nav.map((item) => (
            <button key={item.path} className={path === item.path ? 'active' : ''} onClick={() => navigate(item.path)}>
              {item.label}
            </button>
          ))}
        </nav>
        <button className="cart" onClick={() => setCartCount((count) => count + 1)}>Cart [{cartCount}]</button>
      </header>
      <main>
        {route.path === '/' && <Home />}
        {route.path === '/shop' && <Shop onAdd={() => setCartCount((count) => count + 1)} />}
        {route.path === '/product' && <Product onAdd={() => setCartCount((count) => count + 1)} />}
        {route.path === '/repair' && <Repair />}
        {route.path === '/field-notes' && <FieldNotes />}
        {route.path === '/support' && <Support />}
      </main>
      <footer className="footer">
        <span>{siteData.businessName || 'Forge'} / {siteData.slug || 'generated-site'}</span>
        <span>{siteData.contactEmail || 'support@example.com'}</span>
      </footer>
    </div>
  );
}

function Home() {
  return (
    <>
      <section className="hero">
        <aside>
          <span>Rated for</span>
          <b>Alpine</b>
          <b>Coastal</b>
          <b>Urban</b>
        </aside>
        <div>
          <p className="eyebrow">Deploy-ready technical commerce</p>
          <h1>{siteData.offer || 'Built for the tenth season.'}</h1>
          <p>{siteData.businessName || 'This brand'} serves {siteData.audience || 'customers who want durable products and clear support routes'}.</p>
          <button onClick={() => navigate('/shop')}>Shop gear</button>
        </div>
      </section>
      <SpecStrip />
      <GearGrid />
    </>
  );
}

function Shop({ onAdd }) {
  return (
    <section className="page">
      <p className="eyebrow">Catalog route</p>
      <h2>Shop {siteData.industry || 'field gear'}</h2>
      <GearGrid onAdd={onAdd} />
    </section>
  );
}

function Product({ onAdd }) {
  return (
    <section className="split-page">
      <div className="product-visual">28K</div>
      <div>
        <p className="eyebrow">Product route</p>
        <h2>{siteData.products[0].name}</h2>
        <p>A deploy-ready product page with specs, price, service promise, and add-to-cart placeholder behavior.</p>
        <button onClick={onAdd}>Add to cart</button>
      </div>
    </section>
  );
}

function Repair() {
  return (
    <section className="page">
      <p className="eyebrow">Service route</p>
      <h2>Repair intake</h2>
      <form className="support-form" onSubmit={(event) => event.preventDefault()}>
        <input placeholder="Name" />
        <input placeholder="Email" />
        <select><option>Product support</option><option>Repair request</option><option>Shipping question</option></select>
        <textarea placeholder="Tell us what happened." />
        <button>Send request</button>
      </form>
    </section>
  );
}

function FieldNotes() {
  return (
    <section className="page">
      <p className="eyebrow">Content route</p>
      <h2>Field notes</h2>
      <div className="notes-grid">
        <article><span>01</span><h3>How the launch was tested</h3><p>Use this route for educational content, stories, or customer proof.</p></article>
        <article><span>02</span><h3>Care guide</h3><p>Keep buyers confident after purchase with clear maintenance content.</p></article>
      </div>
    </section>
  );
}

function Support() {
  return (
    <section className="page narrow">
      <p className="eyebrow">Support route</p>
      <h2>Support center</h2>
      <p>Shipping, warranty, returns, sizing, and contact blocks can be wired to real services after deploy.</p>
    </section>
  );
}

function SpecStrip() {
  return (
    <section className="spec-strip">
      <div><span>Build</span><b>Vite React</b></div>
      <div><span>Routes</span><b>6 ready</b></div>
      <div><span>Secrets</span><b>None</b></div>
    </section>
  );
}

function GearGrid({ onAdd = () => navigate('/product') }) {
  return (
    <section className="gear-grid">
      {siteData.products.map((product) => (
        <article key={product.name}>
          <div className="gear-image">{product.spec}</div>
          <h3>{product.name}</h3>
          <p>{product.spec}</p>
          <div>
            <span>{product.price}</span>
            <button onClick={onAdd}>Add</button>
          </div>
        </article>
      ))}
    </section>
  );
}
